# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main_corrector.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets', 'assets'),
        ('utils', 'utils'),
        ('api_clients', 'api_clients'),
        ('VERSION', '.'),
    ],
    hiddenimports=[
        'customtkinter',
        'customtkinter.windows',
        'customtkinter.windows.widgets',
        'pystray',
        'pystray._win32',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'pyperclip',
        'pynput',
        'pynput.keyboard',
        'pynput.mouse',
        'keyboard',
        'httpx',
        'openai',
        'anthropic',
        'google.generativeai',
        'google.genai',
        'google.genai.types',
        'certifi',
        'urllib3',
        'idna',
        'charset_normalizer',
        'sniffio',
        'h11',
        'anyio',
        'typing_extensions',
        'darkdetect',
        'queue',
        'threading',
        'tkinter',
        'tkinter.messagebox',
        'configparser'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt6',
        'PyQt5',
        'PySide6',
        'tkinter.test',
        'test',
        'unittest',
        'pydoc',
        'doctest'
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='popraw_tekst_corrector',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico'
)
